<a href="https://colab.research.google.com/github/ayushmannoterror-source/customer-call-list-cleaning/blob/main/projectv2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Cleaning "Customer Call List.xlsx"

Importing the necessary libraries

In [104]:
import pandas as pd

Getting the data from a given Excel file

In [105]:
df = pd.read_excel("Customer Call List.xlsx")

Preview of the Data

In [106]:
df.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True

Dropping the duplicates

In [107]:
df = df.drop_duplicates()

Dropping non-useful columns

In [108]:
df.drop(columns = "Not_Useful_Column",inplace = True)

Fixing the column "Last_Name"

In [109]:
df["Last_Name"] = df["Last_Name"].str.strip("1._/")

Fixing the column "Phone_Number"

In [110]:
df["Phone_Number"] = df["Phone_Number"].str.replace("-","")
df["Phone_Number"] = df["Phone_Number"].str.replace("|","")
df["Phone_Number"] = df["Phone_Number"].str.replace("/","")
df["Phone_Number"] = df["Phone_Number"].apply(lambda x : str(x))
df["Phone_Number"] = df["Phone_Number"].apply(lambda x : x[0:3] + "-" + x[3:6] + "-" + x[6:10])

Splitting the "Address" column into three more intuitive columns

In [111]:
df[["Street_Name","State","Zip"]] = df["Address"].str.split(",",n = 2,expand = True)
df["State"] = df["State"].str.strip()
df["Zip"] = df["Zip"].str.strip()

Standardising columns "Paying Customer" And "Do_Not_Contact"

In [112]:
df["Paying Customer"] = df["Paying Customer"].replace("Yes","Y")
df["Paying Customer"] = df["Paying Customer"].replace("No","N")
df["Do_Not_Contact"] = df["Do_Not_Contact"].replace("Yes","Y")
df["Do_Not_Contact"] = df["Do_Not_Contact"].replace("No","N")

Marking blank "Do_Not_Contact" values as "Y", then removing all Do Not Contact customers

In [113]:
df["Do_Not_Contact"] = df["Do_Not_Contact"].fillna("Y")
df = df[df["Do_Not_Contact"] != "Y"]

Dropping rows with null value in "Phone_Number"

In [114]:
df["Phone_Number"] = df["Phone_Number"].replace(["nan--", "Na--"], "")
df = df[df["Phone_Number"]!= ""]

Resetting the Index

In [115]:
df = df.reset_index(drop = True)
df.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Name,State,Zip
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,None
1,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,None,None
2,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,None,None
3,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,None
4,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,None,None

Getting the cleaned data in a CSV file

In [116]:
df.to_csv("cleaned_customer_list.csv", index=False)

# Changes Made:
*   Fixed names
*   Standardized phones
*   Split address
*   Removed duplicates
*   Removed Do Not Contact customers